swagger: "2.0"
definitions:
  expireResourceName:
    x-jcloud-module: renewal
    title: ExpireResourceName
    type: object
    properties:
      expireResourceNameList:
        type: array
        items:
          type: string
